#!/bin/bash
sudo apt-get install python-reportlab
wget http://www.rabbitmq.com/releases/rabbitmq-server/v1.7.0/rabbitmq-server_1.7.0-1_all.deb
sudo dpkg -i rabbitmq-server_1.7.0-1_all.deb
sudo /etc/init.d/rabbitmq-server start
sudo rabbitmqctl add_user tiger h0k3yp0k3y
sudo rabbitmqctl add_vhost tiger
sudo rabbitmqctl set_permissions -p tiger tiger "" ".*" ".*"
