#!/bin/bash
sudo apt-get install rabbitmq-server
sudo /etc/init.d/rabbitmq-server start
rabbitmqctl add_user tiger h0k3yp0k3y
rabbitmqctl add_vhost tiger
rabbitmqctl set_permissions -p tiger tiger "" ".*" ".*"

../bin/easy_install authorize
../bin/easy_install django-imagekit
../bin/easy_install django_extensions
../bin/easy_install django-haystack
../bin/easy_install Whoosh
../bin/easy_install celery
cd ../
svn co http://code.djangoproject.com/svn/django/trunk/
cd trunk
../bin/python setup.py install
